title: Sebastian's Blog 
subtitle: Thoughts, stories and ideas.
cover_image: https://images.unsplash.com/photo-1504387103978-e4ee71416c38?auto=format&fit=crop&w=334&q=60&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D

author:
  profile_image:
  url: "/"
  name: GitHub User
  bio: I use jekyll for blogging

email: SebastianColie177@gmail.com

description: > # this means to ignore newlines until the next setting
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

twitter_username: jekyllrb
github_username:  jekyll

permalink: /:year/:month/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      class_name: "post-template"
  -
    scope:
      path: ""
      type: "pages"
    values:
      class_name: "page-template"

# Build settings
markdown: kramdown
theme: caspertwo
exclude:
  - Gemfile
  - Gemfile.lock
